### ISSUE TITLE
Fill the gap between the current launcher and existing launcher

### ISSUE THREAD

**Issue by HirotoShioi** [input-output-hk/cardano-shell#262]
There are some features missing for the current launcher to be replaced with the existing launcher.
A good start will be to analyze the existing launcher (how it behaves), document it, then find out what's missing in the current launcher.

Existing launcher: https://github.com/input-output-hk/cardano-sl/blob/develop/tools/src/launcher/Main.hs

- [x] Setup env vars https://github.com/input-output-hk/cardano-shell/pull/290
- [x] Acquire path to config file via CLI https://github.com/input-output-hk/cardano-shell/pull/275
- [x] Env var substitution (#276)
- [x] Setup working directory https://github.com/input-output-hk/cardano-shell/issues/292
- [x] Setup logging (#269)
- [x] Generate TLS certificate https://github.com/input-output-hk/cardano-shell/pull/77
- [x] Run updater https://github.com/input-output-hk/cardano-shell/pull/241
- [x] Run wallet 
- [ ] Lookup`safemode.yaml` file to see if wallet needs to run in GPU safe mode.
- [x] Clean up logging
- [x] Exit the process

Regarding the checklist, I will make github issues for the one that are unchecked.

**Comment by HirotoShioi** [comment]
We only care about `frontendOnlyScenario`.
https://github.com/input-output-hk/cardano-sl/blob/develop/tools/src/launcher/Main.hs#L341
This will setup everything that's needed to launch the `daedalus-frontend` .

**Comment by HirotoShioi** [comment]
`main`
https://github.com/input-output-hk/cardano-sl/blob/develop/tools/src/launcher/Main.hs#L283-L327

`main` calling `frontendOnlyScenario`
https://github.com/input-output-hk/cardano-sl/blob/develop/tools/src/launcher/Main.hs#L340-L346

`frontendOnlyScenario`
https://github.com/input-output-hk/cardano-sl/blob/develop/tools/src/launcher/Main.hs#L525-L537

**Comment by CodiePP** [comment]
the launcher started:
```
/nix/store/mjd5h5kq0rm9mawpgi77j5pdmvvf5qf5-cardano-daedalus-bridge-3.0.1/bin/cardano-launcher --config /nix/var/nix/profiles/profile-mainnet/etc/launcher-config.yaml
```
its config file:
```
walletLogging: false
nodeArgs:
- --tlsca
- ${XDG_DATA_HOME}/Daedalus/mainnet/tls/server/ca.crt
- --tlscert
- ${XDG_DATA_HOME}/Daedalus/mainnet/tls/server/server.crt
- --tlskey
- ${XDG_DATA_HOME}/Daedalus/mainnet/tls/server/server.key
- --no-client-auth
- --log-console-off
- --update-server
- https://update-cardano-mainnet.iohk.io
- --keyfile
- ${XDG_DATA_HOME}/Daedalus/mainnet/Secrets/secret.key
- --topology
- ${DAEDALUS_CONFIG}/wallet-topology.yaml
- --wallet-db-path
- ${XDG_DATA_HOME}/Daedalus/mainnet/Wallet
- --update-latest-path
- ${XDG_DATA_HOME}/Daedalus/mainnet/installer.sh
- --wallet-address
- 127.0.0.1:0
- --update-with-package
statePath: ${XDG_DATA_HOME}/Daedalus/mainnet
walletPath: daedalus-frontend
nodePath: cardano-node
launcherLogsPrefix: ${XDG_DATA_HOME}/Daedalus/mainnet/Logs/
walletArgs: []
reportServer: http://report-server.cardano-mainnet.iohk.io:8080
nodeDbPath: ${XDG_DATA_HOME}/Daedalus/mainnet/DB/
updaterPath: /bin/update-runner
workingDir: ${XDG_DATA_HOME}/Daedalus/mainnet
frontendOnlyMode: true
nodeLogPath: null
updaterArgs: []
logsPrefix: ${XDG_DATA_HOME}/Daedalus/mainnet/Logs
configuration:
  seed: null
  filePath: ${DAEDALUS_CONFIG}/configuration.yaml
  key: mainnet_wallet_linux64
  systemStart: null
updateArchive: ${XDG_DATA_HOME}/Daedalus/mainnet/installer.sh
nodeLogConfig: ${DAEDALUS_CONFIG}/log-config-prod.yaml
nodeTimeoutSec: 60
updateWindowsRunner: null
tlsPath: ${XDG_DATA_HOME}/Daedalus/mainnet/tls
x509ToolPath: cardano-x509-certificates
```
