### ISSUE TITLE
Manually test the launcher on all platforms

### ISSUE THREAD

**Issue by HirotoShioi** [input-output-hk/cardano-shell#336]
Manually test the cardano-launcher on all platforms.

Note: `I have tested the update system and it works as intended.` Means I have tested the update system by launching Daedalus and see if it executes installer file/script.

## Windows

- [x] I have tested and confirmed that the cardano-launcher works as intended
- [x] I have tested the update system and it works as intended.

## Linux

- [x] I have tested and confirmed that the cardano-launcher works as intended
- [ ] I have tested the update system and it works as intended.

## Mac

- [x] I have tested and confirmed that the cardano-launcher works as intended
- [x] I have tested the update system and it works as intended.

**Comment by HirotoShioi** [comment]
Some issue showed up while testing on Windows

https://github.com/input-output-hk/cardano-shell/issues/332
https://github.com/input-output-hk/cardano-shell/issues/329

**Comment by HirotoShioi** [comment]
On Windows, `launcher-config.yaml` had to be modified for the launcher to operate.

```
walletLogging: true
nodeArgs:
- --tlsca
- tls/server/ca.crt
- --tlscert
- tls/server/server.crt
- --tlskey
- tls/server/server.key
- --no-client-auth
- --log-console-off
- --update-server
- https://update-cardano-mainnet.iohk.io
- --keyfile
- Secrets-1.0\secret.key
- --topology
- ${DAEDALUS_INSTALL_DIRECTORY}\wallet-topology.yaml
- --wallet-db-path
- Wallet-1.0
- --update-latest-path
- Installer.exe
- --wallet-address
- 127.0.0.1:0
- --update-with-package
statePath: ${APPDATA}\Daedalus
nodePath: ${DAEDALUS_INSTALL_DIRECTORY}\cardano-node.exe
launcherLogsPrefix: Logs\pub
walletArgs: []
nodeDbPath: DB-1.0
workingDir: ${APPDATA}\Daedalus
frontendOnlyMode: true
nodeLogPath: null
logsPrefix: Logs
configuration:
  seed: null
  filePath: ${DAEDALUS_INSTALL_DIRECTORY}\configuration.yaml
  key: mainnet_wallet_win64
  systemStart: null
updateArchive: Installer.exe
updaterArgs: []
updaterPath: Installer.bat
walletPath: ${DAEDALUS_INSTALL_DIRECTORY}\Daedalus.exe
nodeLogConfig: ${DAEDALUS_INSTALL_DIRECTORY}\log-config-prod.yaml
nodeTimeoutSec: 60
tlsPath: tls
x509ToolPath: ${DAEDALUS_INSTALL_DIRECTORY}\cardano-x509-certificates.exe
Collapse
```
